#!/bin/bash

cd $(dirname "$0")

for line in $(find . -regextype posix-extended -regex '.*\.(jpg|png)'); do 

    filename=`echo $line | sed -e 's/^.*\///g'`
    
    newfile="_$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c10)_$filename"
    
    
    h=$(identify -ping -format '%H' "$line")
    w=$(identify -ping -format '%W' "$line")
    
    if [ "$h" -gt 500 ] || [ "$w" -gt 500 ]; then
        convert "$line" -resize 500x500\> "$newfile" && \
        rm "$line" && \
        mv "$newfile" "$line" 
        
        echo "$line";
    fi
    
done
